### ISSUE TITLE
Homopolymer compression?

### ISSUE THREAD

**Issue by gevro** [nanopore-wgs-consortium/CHM13#12]
Hi, Has the CHM13 v1 reference undergone homopolymer compression? What is the recommended way to align PacBio Hifi reads to this reference? Are standard pbmm2 settings ok?

**Comment by skoren** [comment]
No, none of the fasta sequences are compressed, only the gfa nodes. I would suggest looking at Winnowmap (https://github.com/marbl/Winnowmap), standard pbmm2 settings would be OK but may do the wrong thing when aligning to repeat regions.
