### ISSUE TITLE
Y chromosome

### ISSUE THREAD

**Issue by colindaven** [nanopore-wgs-consortium/CHM13#13]
Hi, 

are you aiming to integrate an existing (or newly assembled) Y chromosome at some point to make this a general purpose genome? Or is this not planned at present ?

I almost used this in a metagenomics reference sequence collection (i.e. for excluding non-microbial reads from the patient) but only just noticed that the Y chromosome was missing.

Thanks for your efforts.
Colin

**Comment by skoren** [comment]
There is no Y chromosome in CHM13 so it can't be finished from this line. We do have plans to use other cell lines to finish Y but in the meantime you can use the Y chromosome from GRCh38.

**Comment by colindaven** [comment]
Ok, thanks!
