### ISSUE TITLE
rel2.fastq.gz md5

### ISSUE THREAD

**Issue by calkan** [nanopore-wgs-consortium/CHM13#2]
Hi @skoren 

Looks like the md5 hash for rel2.fastq.gz is written incorrectly. It is 35 characters in the README file. The first 3 characters seem to be a mistake (26s), the remainder is what I get when I calculate the hash (7e3f4ded02d500a3db0c76c84cdc42b9)

**Comment by skoren** [comment]
Yep, it should be 7e3f4ded02d500a3db0c76c84cdc42b9.
