### ISSUE TITLE
Centromere AND segmental duplication BED flie 

### ISSUE THREAD

**Issue by zhoudreames** [nanopore-wgs-consortium/CHM13#22]
Hi, Are you provide me a BED file of centromere locations and segmental duplication? I want to use this flie to analysis repeat sequence feature. Thank you so much !!

**Comment by zhoudreames** [comment]
Hi, Are you provide me  a BED file of centromere locations and segmental duplication? I want to use this flie to analysis repeat sequence feature. Thank you so much !!

**Comment by zhoudreames** [comment]
@skoren @snurk @aphillippy could you help me ? thank you~

**Comment by skoren** [comment]
Not yet, these are in progress and being validated. I expect they'll be public by spring. When these are available, they'll likely be available through the UCSC browser.

**Comment by zhoudreames** [comment]
> Not yet, these are in progress and being validated. I expect they'll be public by spring. When these are available, they'll likely be available through the UCSC browser. In the meantime, there is a RepeatMasker track for v1.0 available.

Hi skoren,how long your CHM13 atrticle will be public,I very expect the article content，thanks~

**Comment by skoren** [comment]
The manuscript should be available as a preprint this month.

**Comment by skoren** [comment]
UCSC browser: http://genome.ucsc.edu/cgi-bin/hgTracks?genome=t2t-chm13-v1.0&hubUrl=http://t2t.gi.ucsc.edu/chm13/hub/hub.txt and manuscript: https://doi.org/10.1101/2021.05.26.445798 are both available now.
