### ISSUE TITLE
The T2T homepage seems to be closed access?

### ISSUE THREAD

**Issue by brainstorm** [nanopore-wgs-consortium/CHM13#3]
"You don't have access to this resource"... in Swedish ;)

https://sites.google.com/ucsc.edu/t2tworkinggroup/
<img width="886" alt="skarmavbild 2019-03-07 kl 15 32 53" src="https://user-images.githubusercontent.com/175587/53932569-4e34fb80-40ee-11e9-9519-24af845a565a.png">

**Comment by skoren** [comment]
The site should be public, I can view it without being logged into any google account as can collaborators both in the UK and US. No idea why it would be denying you access. Try the standard clear cache/different browser/logging out of your google account?

**Comment by brainstorm** [comment]
Works now, thanks!
