### ISSUE TITLE
Access to ONT fasta format reads?

### ISSUE THREAD

**Issue by bitcometz** [nanopore-wgs-consortium/CHM13#4]
Hello, 
The fast5 for ONT data is so big.
Is there any access to all the ONT reads or  the long ONT reads (99 Gbp of data in reads >50 kbp, 32x) in the format of "fasta.gz".
It would be much more convenient to download the data and usually doing assembly or SV detection will not need the quality information.

Thanks!

**Comment by skoren** [comment]
There is a fastq.gz file for the all the reads, it's 140g zipped so you could just extract the reads >50kb from there? Is that not sufficient for what you want to do?

**Comment by bitcometz** [comment]
Thanks ! Could you give the URL to download the 140g zipped file.

Best

**Comment by skoren** [comment]
It's in the readme under the rel2 section: https://github.com/nanopore-wgs-consortium/CHM13#rel2-genomic-dna. There are also instructions to download via AWS tools for faster transfer though wget will work on the posted links.
