### ISSUE TITLE
Rel3 Ultra-long vs regular ONT

### ISSUE THREAD

**Issue by mvollger** [nanopore-wgs-consortium/CHM13#6]
Hi Sergey, 

Do you have fastqs for the ultra long data and the regular ont data as two separate datasets, or a way to figure that out from the rel3 fastq.gz? 

I am trying to build length distributions for the different datasets. 

Thanks!
Mitchell

**Comment by skoren** [comment]
I added IDs from each sequencing location for the rel3 data here:
```
https://s3.amazonaws.com/nanopore-human-wgs/chm13/nanopore/rel3/ids/nhgri.ids.gz
https://s3.amazonaws.com/nanopore-human-wgs/chm13/nanopore/rel3/ids/ucd.ids.gz
https://s3.amazonaws.com/nanopore-human-wgs/chm13/nanopore/rel3/ids/unottingham.ids.gz
https://s3.amazonaws.com/nanopore-human-wgs/chm13/nanopore/rel3/ids/uwashington.ids.gz
```

Will add these to the readme in the next update.
